name: docker publish

on:
  # allow manually run the action:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Make package
        run: | 
          git clone https://github.com/apache/iotdb.git
          cd iotdb
          git checkout v1.3.2
          sed -i 's/  && mv \${target} iotdb/# \&\& mv \${target} iotdb/' docker/src/main/Dockerfile-1.0.0-datanode
          sed -i 's/#  \&\& mv apache-iotdb-\${version}-server-bin iotdb/  \&\& mv apache-iotdb-\${version}-server-bin iotdb/' docker/src/main/Dockerfile-1.0.0-datanode
          cat docker/src/main/Dockerfile-1.0.0-datanode
          cd docker/src/main
          mkdir target
          cd target
          wget https://dlcdn.apache.org/iotdb/1.3.2/apache-iotdb-1.3.2-all-bin.zip
          wget https://dlcdn.apache.org/iotdb/1.3.2/apache-iotdb-1.3.2-confignode-bin.zip
          wget https://dlcdn.apache.org/iotdb/1.3.2/apache-iotdb-1.3.2-datanode-bin.zip
          cd ../DockerCompose
          sed -i 's/ docker run --rm --privileged tonistiigi/# docker run --rm --privileged tonistiigi/' do-docker-build.sh
          sed -i 's/--platform=$TARGETPLATFORM//g' do-docker-build.sh
          ./do-docker-build.sh -t all -v 1.3.2 -p
          

